/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package noir;

import java.util.HashMap;

public class App {
    public static String CIRCUIT_BYTECODE = "H4sIAAAAAAAA/9VY23KCMBDdcFGrbdU+9sn2CxIgEN76K4D42f2UTs002BBj2yknzrgzTCKDZ092N5sDjL7s6Xg907cxM76ZkU8zwQymi5vzsij6KutFLhqe1a2SvJBtqYQSUsl9pvK8V4Wq6raueC2KvBcHWecHAxzhOPLU4ER0buh4ALG4h+5UbDFM7FjEZkyseKAcnhwz40hf78ZRbJzuHJ9xwKT8szAzU5giJlyRJxSmWCJw/JBrTj1YLe/2UrTlvhJ9I1XX1bkQWVM2ZZupQ99KoaQ6YnZNpo7usqYTPW/KPqVx87ENvbFTHBa3+c4o4KYLFYhZANw5sMhCrXuOz5GXK6KxaK6oRjDgInO0IOyG0k1KY74cL9+JD66HIiK/8uHTrGKE3f+uTcT2Kog7My7pCgpCO7MVhHa6C5RkZooIvUG3FObkT7DrHxXjVOV0B4zfElhXwFyMNhxahSHjt6LbVGErCqPC7unGVNjKIY3CfQAWWah1P+BzFESFLQ1XtApD5uiR8CpMYw4qLCL/d5cIHGvgq7QAHC4nleRZehAFtjbjhq6gwLSTneMjuZGETlUxa+AaN4EKDd3I1uAaShye9tynIk4fBGfOqO2n7pJ4HNhzuzv9RmaYrzx+tp57cw9Xd3EL6/kPwp5mQ8xSD7eEzmO6sPgBuYwkcUznMdh64rNwuNncL/3W9krj1zVm3WfWf2Jzz/Vry9jIwrv0DLuA89ca+QRdyNsVphkAAA==";

    static {
        // This actually loads the shared object that we'll be creating.
        // The actual location of the .so or .dll may differ based on your
        // platform.
        System.loadLibrary("noir_java");
    }

    // The rest is just regular ol' Java!
    public static void main(String[] args) {
        System.out.println("Initializing witness...");
        HashMap<String, String> initial_witness = new HashMap<String, String>();
        initial_witness.put("0", "0x2f");
        initial_witness.put("1", "0x02");

        System.out.println("Generating proof...");
        Proof proof = Noir.prove(CIRCUIT_BYTECODE, initial_witness);

        System.out.println("Verifying proof...");
        boolean verdict = Noir.verify(CIRCUIT_BYTECODE, proof);

        assert verdict;
        System.out.println("Proof correct");
    }
}
